ARG BUILDER_IMAGE
ARG RUNTIME_IMAGE

FROM $BUILDER_IMAGE AS builder
WORKDIR /go/src/github.com/aws/amazon-eks-pod-identity-webhook
COPY . .
ENV GO_PACKAGE github.com/aws/amazon-eks-pod-identity-webhook
RUN make amazon-eks-pod-identity-webhook

FROM $RUNTIME_IMAGE
RUN microdnf -y update && \
    microdnf clean all && \
    rm -rf /var/cache/yum
COPY --from=builder /go/src/github.com/aws/amazon-eks-pod-identity-webhook/amazon-eks-pod-identity-webhook /usr/bin/aws-pod-identity-webhook
